version: '3.8'
services:
  chat-service:
    image: chat-service
    build:
      dockerfile: Dockerfile_Dev
    container_name: chat-service
    restart: always
    ports:
      - 3000:3000
    environment:
      - MONGODB_USERNAME=rootuser
      - MONGODB_PASSWORD=rootpass
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=random_chat
