version: '3.8'
services:
  chat-service:
    image: chat-service
    build:
      dockerfile: Dockerfile_Dev
    container_name: chat-service
    restart: always
    ports:
      - 3000:3000
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=random_chat
      - STAGE=local
