version: '3.8'

volumes:
  microservice_db_data:

services:
  postgres:
    image: postgres:14.7
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=random_chat
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
